minimum_pre_commit_version: "3.0.0"

repos:
  - repo: local
    hooks:
      - id: bashly-shell-validation
        name: bashly source validation
        entry: .scripts/pre-commit-ci.sh --mode=check --project-root .
        language: system
        pass_filenames: false
        stages: [pre-commit]
        files: ^(src/.*|bashly(?:-settings)?\.yml|settings\.yml|\.scripts/pre-commit-ci\.sh)$
